#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun 20 10:58:54 2019

@author: renuka
"""

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt
from math import *
from mpl_toolkits.mplot3d import Axes3D

def model(k, t, M):
    x, y, z = k
    dxdt = 4**y
    dydt = 4*x-y*M
    dzdt = 56
    return(dxdt, dydt, dzdt)

k0 = [0, 0, 0]
t = np.linspace(0, 10, 100)
M = 56

kk = odeint(model, k0, t, args=(M,))
X = kk[:, 0]
Y = kk[:, 1]
Z = kk[:, 2]


fig = plt.figure(2)
ax = fig.add_subplot(111, projection='3d')

u = np.linspace(0, 2 * np.pi, 100)
v = np.linspace(0, np.pi, 100)

r = 10

x = r * np.outer(np.cos(u), np.sin(v))
y = r * np.outer(np.sin(u), np.sin(v))
z = r * np.outer(np.ones(np.size(u)), np.cos(v))
ax.plot_surface(x, y, z, rstride=4, cstride=4, color='k')

plt.plot(X, Y, Z)
plt.show()
    
