#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun  5 10:48:08 2019

@author: renuka
"""

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt
from math import *
from mpl_toolkits.mplot3d import Axes3D

def func(f, T, M):
    # f
    t, r, theta, phi, pt, pr, ptheta, pphi = f
    # derivatives
    dpthetadT = (cos(theta)*(ptheta)**2)/((r**2)*sin(phi)**3)
    dprdT = (pphi**2/r**3)-(M/(r-2*M)**2)-((M*pr**2)/r**2)
    dtdT = (1+(2*M/r))*pt
    drdT = (1-(2*M/r)*pr)
    dthetadT = ptheta/(r**2)
    dphidT = pphi/((r**2)*(sin(theta)**2))
    return np.array([dtdT, drdT, dthetadT, dphidT, dptdT, dprdT, dpthetadT, dpphidT])

# initial conditions and constants
pt = -1
dptdT = 0
ptheta = 0
dpphidT = 0
M = 9999
t0 = 0
r0 = 4790
theta = np.radians(pi/2)
phi0 = np.radians(pi/4) # angular momentum p = "amount of rotational motion"
pr0 = 0.5
ptheta0 = 0
pphi0 = 0.7

f0=array([t0, r0, theta, phi0, pt, pr0, ptheta0, pphi0]) # initial conditions, necessary to find the constants after the return operation 

T = np.linspace(-1000, 900, 900) # time variation between -1000s and 900s with a total of 900 calculations

xx=odeint(func, f0, T, args=(M,)) # generate the solution, args=() is to add M to the equations

r = xx[:, 1]
theta = xx[:, 2]
phi = xx[:, 3]

# spherical to cartesian coordinates 
X = r * np.cos(phi) * np.sin(theta)
Y = r * np.sin(phi) * np.sin(theta)
Z = r * np.cos(theta)
fig = plt.figure()
ax = fig.add_subplot(1,1,1, projection="3d")
plot = ax.plot_trisurf(X, Y, Z, linewidth=0, antialiased=False)

# T2 = np.linspace(-1000, 900, 900)
# k0=array([r0*np.cos(phi0)*np.sin(theta), r0*np.sin(phi0)*np.sin(theta), r0*np.cos(theta)])
# yy=odeint(sph2cart, k0, T2, args=(r, theta, phi))
# yy=map(sph2cart, xx[:, 1], xx[:, 2], xx[:, 3]) #map isn't a list => needs to be a list ¿ # to apply sph2cart to every r, theta and phi value

plt.show()
